### ISSUE TITLE
object 'JAM_output' not found

### ISSUE THREAD

**Issue by jordanero** [jennasimit/MGflashfm#3]
Hello!

Thanks for making this software. I'm trying to use MGfm for single-trait, multi-ancestry fine-mapping. 

I'm having a hard time getting the example to work (also having a hard time with my data, but I figured I would start with the example). When I run the following code (taken from the demonstration on the website):

require(MGflashfm)
T1gwas.list <- list(gwas.list[[1]][[1]], gwas.list[[2]][[1]])
N1all <- sapply(Nall,function(x) x[1])
save.path <- '/n/scratch3/users/j/jor6523/mgfm'
mgCS1 <- MGFMwithJAM(T1gwas.list, corX.list,  N1all, save.path,cpp=0.99,cred=0.99, maxcv=1, maxcv_stop = 20, maxcv_autocheck = TRUE,NCORES=1,jam.nM.iter=1)

I get the following error message:

Error in JAMcor.tries.maxcv(beta.list[[i]], corX.list[[i]], raf.list[[i]],  :
  object 'JAM_output' not found
Calls: MGFMwithJAM -> <Anonymous> -> lapply -> FUN -> JAMcor.tries.maxcv
Execution halted 

Do you have any idea why the example might not be working for me? I installed the package today using  a fresh R 4.3.1 on a CentOS Linux machine. I've attached a file with the full output in case that's of any help.
[err.txt](https://github.com/jennasimit/MGflashfm/files/13505992/err.txt)

Thanks!
Jordan

**Comment by jennasimit** [comment]
Thanks for your email. Great that you are trying out MGfm, but sorry to hear that you have had problems running it.
 
The issue is that it also requires the R2BGLiMS library to be loaded:

require(MGflashfm)
require(R2BGLiMS)
 
These libraries are shown at the start of the multi-group example section, but I will add them to the start of the MGfm example code as well.

* Solved off-line, but adding in detail here
