### ISSUE TITLE
Error message associated with "maxcv_autocheck"

### ISSUE THREAD

**Issue by ZikunY** [jennasimit/MGflashfm#5]
Hi Dr. Asimit, 

 I encountered another issue here. If I switched the option of "maxcv_autocheck" to "F" or "FALSE", the function "JAMdynamic" or "MGFMwithJAM" would return the error message "object 'JAM_output' not found". I have loaded both packages "MGflashfm" and "R2BGLiMS". It seems the function would work only with "maxcv_autocheck" setting to "TRUE". Could you let me know if I did something wrong here? Thank you for your time. 

Best,
Zikun

**Comment by ZikunY** [comment]
Just want to follow up on this issue. Here is the running log

_g1t1CS <- JAMdynamic(gwas=gwas.list[[1]],corX=ld.list[[1]], ybar=0, Vy=1, N=3000, cred=.99, save.path=save.path, maxcv=1, maxcv_stop = 2, maxcv_autocheck = T,jam.nM.iter=1)

2277 SNPs have been grouped into 1611 bins
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at Jama.Matrix.<init>(Matrix.java:85)
	at Objects.Data.<init>(Data.java:527)
	at bglims.BGLiMS.main(BGLiMS.java:81)
[1] "Keep trying maxcv by adding 1 ..., maxcv == 2"
[1] "The maxcv_stop reached, no result!"
[1] "Keep trying maxcv by adding 1 ..., maxcv == 2"
[1] "The maxcv_stop reached, no result!"
Error in JAMcor.tries.maxcv(beta1, corX, raf, ybar, Vy, N, save.path,  : 
  object 'JAM_output' not found_

I got this error message of "JAM_output" not found. Please note that the number of variants stored in this dataset is over 2700. However, if I switched to another dataset with only 400+ variants, there was no error message. Please let me know what I can do here. 

Best,
Zikun

**Comment by jennasimit** [comment]
Dear Zikun,
 
Thanks for your detailed running log. 
 
The maxcv_autocheck argument was a test feature, and should always be set to TRUE, as you have found; I will update the documentation for this. Also, you have correctly set maxcv_stop > maxcv.
 
It is good that you are getting output for the smaller region. The error that you are getting for the larger region is due to the configuration of your memory setting on your Linux VM. 
These functions have successfully run on regions with > 3000 variants using Windows and Mac systems, as well as on the hpc. I suggest that you try to change your memory configuration or try an alternative platform to run your analysis.
 
Hope that this helps and good luck with your research.
 
Best wishes,
Jenn

**Comment by ZikunY** [comment]
Thank you, Dr. Asimit! Your help is greatly appreciated here!

Best,
Zikun
